title:        pangzhen的专栏
description: 既然选择了远方，便只顾风雨兼程！
show_downloads: true

baseurl: "/android" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://pangzhen.github.io" # change this to the base hostname & protocol for your site

google_analytics:
# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
  date_format: "%Y-%m-%d"

theme: # leave it empty

# social
author: "胖真"
image: /thumbnail-jumbo.png
twitter:
  username: 
#  site:
facebook:
  #publisher: 
  #profile_id: 
  app_id: 
  #authors: 
#  admins:
